version: '3.8'

services:
  broker:
    image: confluentinc/cp-kafka:7.4.1
    container_name: broker
    hostname: broker
    ports:
      - "9092:9092"
    
    environment:
      # broker identity
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      CLUSTER_ID: MkU30EVBNTcwNTJENDM2Qk
      
      # COM chanels
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: HOST://0.0.0.0:29092,CLIENT://broker:9092,INTERNAL://broker:29093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:29092,CLIENT://broker:9092

      # Kafka general configuration.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: HOST
      
      # Resource manager configuration : kraft mode
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: INTERNAL
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:9092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

    volumes:
      - ./registry/:/etc/tutoregistry/

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    
    depends_on:
      - broker

    environment:
      KAFKA_CLUSTERS_0_NAME: local 
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
      DYNAMIC_CONFIG_ENABLED: 'true'