version: '3.8'

services:
  broker1:
    image: confluentinc/cp-kafka:7.4.1
    container_name: broker1
    hostname: broker1
    ports:
      - "9091:9092"
    
    environment:
      # broker1 identity
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      CLUSTER_ID: MkU30EVBNTcwNTJENDM2Qk
      
      # COM chanels
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: HOST://0.0.0.0:29092,CLIENT://broker1:9092,INTERNAL://BROKER1:29093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:29092,CLIENT://broker1:9092

      # Kafka general configuration.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: HOST
      
      # Resource manager configuration : kraft mode
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker1:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: INTERNAL
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

  broker2:
    image: confluentinc/cp-kafka:7.4.1
    container_name: broker2
    hostname: broker2
    ports:
      - "9092:9092"
    
    environment:
      # Broker identity
      KAFKA_BROKER_ID: 2
      KAFKA_NODE_ID: 2
      CLUSTER_ID: MkU30EVBNTcwNTJENDM2Qk
      
      # COM chanels
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: HOST://0.0.0.0:29092,CLIENT://broker2:9092,INTERNAL://BROKER2:29093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:29092,CLIENT://broker2:9092

      # Kafka general configuration.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: HOST
      
      # Resource manager configuration : kraft mode
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker1:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: INTERNAL
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs

  broker3:
    image: confluentinc/cp-kafka:7.4.1
    container_name: broker3
    hostname: broker3
    ports:
      - "9093:9092"
    
    environment:
      # Broker identity
      KAFKA_BROKER_ID: 3
      KAFKA_NODE_ID: 3
      CLUSTER_ID: MkU30EVBNTcwNTJENDM2Qk
      
      # COM chanels
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: HOST://0.0.0.0:29092,CLIENT://broker3:9092,INTERNAL://BROKER3:29093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:29092,CLIENT://broker3:9092

      # Kafka general configuration.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: HOST
      
      # Resource manager configuration : kraft mode
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker1:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: INTERNAL
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    
    depends_on:
      - broker1
      - broker2
      - broker3

    environment:
      KAFKA_CLUSTERS_0_NAME: local 
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker1:9091, broker2:9092, broker3:9093
      DYNAMIC_CONFIG_ENABLED: 'true'